/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venta;

import java.util.ArrayList;

/**
 *
 * @author awerito1994
 */
public class IngresarProd extends javax.swing.JFrame {

    /**
     * @return the titulo
     */
    public static javax.swing.JLabel getTitulo() {
        return titulo;
    }

    /**
     * @param aTitulo the titulo to set
     */
    public static void setTitulo(javax.swing.JLabel aTitulo) {
        titulo = aTitulo;
    }

    /**
     * @return the sw
     */
    public static javax.swing.JTextField getSw() {
        return sw;
    }

    /**
     * @param aSw the sw to set
     */
    public static void setSw(javax.swing.JTextField sw) {
        sw = sw;
    }

    public void limpiar() {
        txtProducto.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
    }


    /**
     * Creates new form IngresarProd
     */
    static ArrayList<Comestible> l1 = new ArrayList<Comestible>();
    static ArrayList<Utencilio> l2 = new ArrayList<Utencilio>();
    static ArrayList<Oficina> l3 = new ArrayList<Oficina>();
    static ArrayList<Industrial> l4 = new ArrayList<Industrial>();

    public IngresarProd() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        prod = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        cant = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        tabla = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        precio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        interfaz2 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        sw = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prod.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        prod.setForeground(new java.awt.Color(0, 0, 0));
        prod.setText("Cantidad:");
        getContentPane().add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtStock.setBackground(new java.awt.Color(60, 63, 65));
        txtStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtStock.setCaretColor(new java.awt.Color(255, 255, 255));
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 30));

        cant.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        cant.setForeground(new java.awt.Color(0, 0, 0));
        cant.setText("Nuevo Producto:");
        getContentPane().add(cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtProducto.setBackground(new java.awt.Color(60, 63, 65));
        txtProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtProducto.setCaretColor(new java.awt.Color(255, 255, 255));
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 130, 30));

        agregar.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(0, 0, 0));
        agregar.setText("AGREGAR");
        agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.setFocusable(false);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 90, -1));

        tabla.setBackground(new java.awt.Color(2, 12, 104));
        tabla.setBorder(null);
        tabla.setForeground(new java.awt.Color(0, 0, 0));

        productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productos.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(0, 0, 0));
        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO"
            }
        ));
        productos.setFocusable(false);
        productos.setGridColor(new java.awt.Color(0, 0, 0));
        productos.setRowHeight(30);
        productos.setShowHorizontalLines(false);
        tabla.setViewportView(productos);

        getContentPane().add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, 150));

        salir.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("SALIR");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, -1));

        precio.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setText("Precio");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 20));

        txtPrecio.setBackground(new java.awt.Color(60, 63, 65));
        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPrecio.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, 30));

        interfaz2.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        interfaz2.setForeground(new java.awt.Color(0, 0, 0));
        interfaz2.setText("ATRAS");
        interfaz2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        interfaz2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        interfaz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interfaz2ActionPerformed(evt);
            }
        });
        getContentPane().add(interfaz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        titulo.setFont(new java.awt.Font("Dubai Light", 1, 22)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        sw.setEnabled(false);
        sw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swActionPerformed(evt);
            }
        });
        getContentPane().add(sw, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    public void mostar() {

        String matriz[][] = new String[l1.size()][3];
        String matriz2[][] = new String[l2.size()][3];
        String matriz3[][] = new String[l3.size()][3];
        String matriz4[][] = new String[l4.size()][3];
        
        int b = Integer.parseInt(getSw().getText());

        switch (b) {
            case 1:

                for (int i = 0; i < l1.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz[i][2] = Double.toString(l1.get(i).getPrecio());
                    matriz[i][1] = Integer.toString(l1.get(i).getStock());
                    matriz[i][0] = l1.get(i).getNombre();                 

                }
        productos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO"
            }
        ));
                break;
            case 2:
                for (int i = 0; i < l2.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz2[i][0] = l2.get(i).getNombre();
                    matriz2[i][1] = Integer.toString(l2.get(i).getStock());
                    matriz2[i][2] = Double.toString(l2.get(i).getPrecio());

                }
                productos.setModel(new javax.swing.table.DefaultTableModel(
                        matriz2,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "PRECIO"
                        }
                ));
                break;
            case 3:
                for (int i = 0; i < l3.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz3[i][0] = l3.get(i).getNombre();
                    matriz3[i][1] = Integer.toString(l3.get(i).getStock());
                    matriz3[i][2] = Double.toString(l3.get(i).getPrecio());

                }
                productos.setModel(new javax.swing.table.DefaultTableModel(
                        matriz3,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "PRECIO"
                        }
                ));
                break;
            case 4:
                for (int i = 0; i < l4.size(); i++) {
                    // Agrego campos a listLabel que es un array
                    matriz4[i][0] = l4.get(i).getNombre();
                    matriz4[i][1] = Integer.toString(l4.get(i).getStock());
                    matriz4[i][2] = Double.toString(l4.get(i).getPrecio());

                }
                productos.setModel(new javax.swing.table.DefaultTableModel(
                        matriz4,
                        new String[]{
                            "PRODUCTO", "CANTIDAD", "PRECIO"
                        }
                ));
                break;

        }

    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        int a = Integer.parseInt(getSw().getText());
        switch (a) {
            case 1:
                String nombre = txtProducto.getText();
                String stock = txtStock.getText();
                String precio = txtPrecio.getText();
                double precio1 = Double.parseDouble(precio);
                int cantidad = Integer.parseInt(stock);
                Comestible obj = new Comestible(precio1, cantidad, nombre);
                obj.setNombre(nombre);
                obj.setStock(cantidad);
                obj.setPrecio(precio1);
                l1.add(obj);
                mostar();
                limpiar();
                break;

            case 2:
                nombre = txtProducto.getText();
                stock = txtStock.getText();
                precio = txtPrecio.getText();
                precio1 = Double.parseDouble(precio);
                cantidad = Integer.parseInt(stock);
                Utencilio obj2 = new Utencilio(precio1,cantidad,nombre);
                obj2.setNombre(nombre);
                obj2.setStock(cantidad);
                obj2.setPrecio(precio1);                
                l2.add(obj2);
                mostar();
                limpiar();
                break;
            case 3:
                nombre = txtProducto.getText();
                stock = txtStock.getText();
                precio = txtPrecio.getText();
                precio1 = Double.parseDouble(precio);
                cantidad = Integer.parseInt(stock);
                Oficina obj3 = new Oficina(precio1, cantidad, nombre);
                obj3.setNombre(nombre);
                obj3.setStock(cantidad);
                obj3.setPrecio(precio1);
                l3.add(obj3);
                mostar();
                limpiar();
                break;
            case 4:
                nombre = txtProducto.getText();
                stock = txtStock.getText();
                precio = txtPrecio.getText();
                precio1 = Double.parseDouble(precio);
                cantidad = Integer.parseInt(stock);
                Industrial obj4 = new Industrial(precio1,cantidad, nombre);
                obj4.setNombre(nombre);
                obj4.setStock(cantidad);
                obj4.setPrecio(precio1);                
                l4.add(obj4);
                mostar();
                limpiar();
                break;
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
    }//GEN-LAST:event_txtProductoKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
    }//GEN-LAST:event_txtStockKeyTyped

    private void interfaz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interfaz2ActionPerformed
        // TODO add your handling code here:
        Interfaz2 a = new Interfaz2();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_interfaz2ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void swActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_swActionPerformed
    public void cargar(Comestible com) {
        this.txtProducto.setText(com.getNombre());
        this.txtStock.setText(Integer.toString(com.getStock()));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel cant;
    private javax.swing.JButton interfaz2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel prod;
    private javax.swing.JTable productos;
    private javax.swing.JButton salir;
    private static javax.swing.JTextField sw;
    private javax.swing.JScrollPane tabla;
    private static javax.swing.JLabel titulo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
