/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venta;

import venta.IngresarProd;
import javax.swing.*;

/**
 *
 * @author awerito1994
 */
public class Interfaz4 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz4
     */
    public Interfaz4() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        muestraNombre = new javax.swing.JLabel();
        muestraStock = new javax.swing.JLabel();
        muestraPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        factura = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto1.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        texto1.setForeground(new java.awt.Color(0, 0, 0));
        texto1.setText("INGRESE UN PRODUCTO A COMPRAR");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        texto2.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 0, 0));
        texto2.setText("Nombre:");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        texto3.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        texto3.setForeground(new java.awt.Color(0, 0, 0));
        texto3.setText("Cantidad:");
        getContentPane().add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtBusqueda.setBackground(new java.awt.Color(0, 0, 0));
        txtBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBusqueda.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, -1));

        txtCant.setBackground(new java.awt.Color(0, 0, 0));
        txtCant.setForeground(new java.awt.Color(255, 255, 255));
        txtCant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCant.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 70, -1));

        buscar.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 0));
        buscar.setText("BUSCAR");
        buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.setFocusable(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        muestraNombre.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        muestraNombre.setForeground(new java.awt.Color(0, 0, 0));
        muestraNombre.setText("---------");
        muestraNombre.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(muestraNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, -1));

        muestraStock.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        muestraStock.setForeground(new java.awt.Color(0, 0, 0));
        muestraStock.setText("---------");
        muestraStock.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(muestraStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, -1));

        muestraPrecio.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        muestraPrecio.setForeground(new java.awt.Color(0, 0, 0));
        muestraPrecio.setText("---------");
        muestraPrecio.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(muestraPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 60, -1));

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("$");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        comprar.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        comprar.setForeground(new java.awt.Color(0, 0, 0));
        comprar.setText("COMPRAR");
        comprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comprar.setFocusable(false);
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        getContentPane().add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, 30));

        factura.setBackground(new java.awt.Color(0, 0, 0));
        factura.setColumns(20);
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setRows(5);
        factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(factura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        atras.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        atras.setForeground(new java.awt.Color(0, 0, 0));
        atras.setText("VOLVER");
        atras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, 30));

        cerrar.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        cerrar.setForeground(new java.awt.Color(0, 0, 0));
        cerrar.setText("SALIR");
        cerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String textoBusqueda = txtBusqueda.getText();
        boolean band = false;
        // Verifica si el nombre esta contenido en el nombre ingresado
        for (Comestible comes : IngresarProd.l1) {
            if (comes.getNombre().contains(textoBusqueda)
                    || comes.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || comes.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {

                band = true;
                muestraNombre.setText(comes.getNombre());
                muestraPrecio.setText(String.valueOf(comes.getPrecio()));
                muestraStock.setText(String.valueOf(comes.getStock()));
            }

        }
        if (band == false) {
            JOptionPane.showMessageDialog(null, "No existe el producto en la seccion de comestibles");
        }

        for (Oficina ofi : IngresarProd.l3) {
            if (ofi.getNombre().contains(textoBusqueda)
                    || ofi.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || ofi.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {

                band = true;
                muestraNombre.setText(ofi.getNombre());
                muestraPrecio.setText(String.valueOf(ofi.getPrecio()));
                muestraStock.setText(String.valueOf(ofi.getStock()));
            }

        }
        if (band == false) {
            JOptionPane.showMessageDialog(null, "No Existe el producto en la seccion oficina");
        }

        for (Industrial in : IngresarProd.l4) {
            if (in.getNombre().contains(textoBusqueda)
                    || in.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || in.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {

                band = true;
                muestraNombre.setText(in.getNombre());
                muestraPrecio.setText(String.valueOf(in.getPrecio()));
                muestraStock.setText(String.valueOf(in.getStock()));
            }

        }
        if (band == false) {
            JOptionPane.showMessageDialog(null, "No Existe el producto en la seccion de utensilios");
        }

        for (Utencilio ut : IngresarProd.l2) {
            if (ut.getNombre().contains(textoBusqueda)
                    || ut.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || ut.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {

                band = true;
                muestraNombre.setText(ut.getNombre());
                muestraPrecio.setText(String.valueOf(ut.getPrecio()));
                muestraStock.setText(String.valueOf(ut.getStock()));
            }

        }
        if (band == false) {
            JOptionPane.showMessageDialog(null, "No Existe el producto en la seccion industrial");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        String textoBusqueda = txtBusqueda.getText();
        int cantidadProductos = Integer.parseInt(txtCant.getText());
        double valorSinIva = 0;
        double valorIva = 0;
        boolean band = false;
        double total = 0;
        // Realiza las operaciones para realizar una compra
        // Setea la nueva cantidad de producto
        for (Comestible comes : IngresarProd.l1) {

            if (comes.getStock()>= cantidadProductos && comes.getNombre().contains(textoBusqueda)
                    || comes.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || comes.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {
                band = true;
                valorSinIva = cantidadProductos * comes.getPrecio();
                total = valorSinIva;
                factura.setText("Producto: " + comes.getNombre()+ "\nSubTotal: "
                        + "$" + String.valueOf(valorSinIva) + "\nValor +IVA: $"
                        + String.valueOf(valorIva) + "\nTotal a pagar: $"
                        + String.valueOf(total));
                comes.setStock(comes.getStock()- cantidadProductos);
                muestraStock.setText(String.valueOf(comes.getStock()));
            }
        }

        if (band == false) {
            JOptionPane.showMessageDialog(null, "No existe el producto en stock de comestibles");
        }
        // Realiza las operaciones para realizar una compra
        // Setea la nueva cantidad de producto
        for (Oficina ofi : IngresarProd.l3) {
            if (ofi.getStock()>= cantidadProductos && ofi.getNombre().contains(textoBusqueda)
                    || ofi.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || ofi.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {
                band = true;
                valorSinIva = cantidadProductos * ofi.getPrecio();
                valorIva = valorSinIva * 0.12;
                total = valorIva + valorSinIva;

                factura.setText("Producto: " + ofi.getNombre()+ "\nSubTotal: "
                        + "$" + String.valueOf(valorSinIva) + "\nValor +IVA: $"
                        + String.valueOf(valorIva) + "\nTotal a pagar: $"
                        + String.valueOf(total));
                ofi.setStock(ofi.getStock()- cantidadProductos);
                muestraStock.setText(String.valueOf(ofi.getStock()));

            }

        }

        if (band == false) {
            JOptionPane.showMessageDialog(null, "No existe el producto en stock de oficina");
        }
        // Realiza las operaciones para realizar una compra
        // Setea la nueva cantidad de producto
        for (Utencilio ut : IngresarProd.l2) {
            if (ut.getStock()>= cantidadProductos && ut.getNombre().contains(textoBusqueda)
                    || ut.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || ut.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {
                band = true;
                valorSinIva = cantidadProductos * ut.getPrecio();
                ut.setStock(ut.getStock()- cantidadProductos);
                valorIva = valorSinIva * 0.12;
                total = valorIva + valorSinIva;

                factura.setText("Producto: " + ut.getNombre()+ "\nSubTotal: "
                        + "$" + String.valueOf(valorSinIva) + "\nValor +IVA: $"
                        + String.valueOf(valorIva) + "\nTotal a pagar: $"
                        + String.valueOf(total));
                ut.setStock(ut.getStock()- cantidadProductos);
                muestraStock.setText(String.valueOf(ut.getStock()));

            }

        }

        if (band == false) {
            JOptionPane.showMessageDialog(null, "No existe el producto en stock de utensilios");
        }
        // Realiza las operaciones para realizar una compra
        // Setea la nueva cantidad de producto
        for (Industrial in : IngresarProd.l4) {
            if (in.getStock()>= cantidadProductos && in.getNombre().contains(textoBusqueda)
                    || in.getNombre().toUpperCase().contains(textoBusqueda.toUpperCase())
                    || in.getNombre().toLowerCase().contains(textoBusqueda.toLowerCase())) {
                band = true;
                valorSinIva = cantidadProductos * in.getPrecio();
                valorIva = valorSinIva * 0.12;
                total = valorIva + valorSinIva;

                factura.setText("Producto: " + in.getNombre()+ "\nSubTotal: "
                        + "$" + String.valueOf(valorSinIva) + "\nValor +IVA: $"
                        + String.valueOf(valorIva) + "\nTotal a pagar: $"
                        + String.valueOf(total));
                in.setStock(in.getStock()- cantidadProductos);
                muestraStock.setText(String.valueOf(in.getStock()));

            }

        }

        if (band == false) {
            JOptionPane.showMessageDialog(null, "No existe el producto en stock de industiales");
        }

    }//GEN-LAST:event_comprarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        Interfaz1 b = new Interfaz1();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton comprar;
    private javax.swing.JTextArea factura;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel muestraNombre;
    private javax.swing.JLabel muestraPrecio;
    private javax.swing.JLabel muestraStock;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
